### ISSUE TITLE
PLZ FIX README CONTRIBUTION-PIC UPDATE

### ISSUE THREAD

**Issue by sainik-khaddar** [sainik-khaddar/MY-LEETCODE-SOLUTIONS#6]
Readme pic update

**Comment by Shubh2003** [comment]
hi please assign me this issue

**Comment by SharyDev** [comment]
Hello, Please Assign this to me.

**Comment by SharyDev** [comment]
I already got fixed. just need 2 minutes to fix it.

**Comment by SharyDev** [comment]
The Fix is already there in the Pull request Please check.

**Comment by sainik-khaddar** [comment]
The issue is not fixed, because in the contributor section of my readme, I want everyone's github profile pic to be displayed. But it's not showing. I have tried with [this site](https://contrib.rocks/preview?repo=angular%2Fangular-ja), but it's not working
