### ISSUE TITLE
Convert Binary Number in a Linked List to Integer (Leetcode-1290)

### ISSUE THREAD

**Issue by bosedipayan** [sainik-khaddar/MY-LEETCODE-SOLUTIONS#63]
Hi @sainik-khaddar, Please assign this to me. I want to add this code in c++ language.

**Comment by VAIBHAV0526** [comment]
can you assign me @sainik-khaddar

**Comment by debapriya36** [comment]
Hi @sainik-khaddar can you please assign the issue to me? I want to code it in C++.
Thank You.
